### ISSUE TITLE
The problem with compiling and running binaries

### ISSUE THREAD

**Issue by cryptomaxsun** [artocash/arto#1]
```
./artod --rpc-bind-ip=127.0.0.1 --rpc-bind-port=19451
Failed to parse arguments: character conversion failed
```

Compilation
```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/arto/build/release/CMakeFiles/CMakeOutput.log".
make: *** [cmake-release] Error 1

arto/build# make
make: *** No targets specified and no makefile found.  Stop.

```
How fix?
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-133-generic x86_64)

**Comment by artocash** [comment]
Hello,

Make sure to install boost either
```
sudo apt-get install libboost1.55-all-dev

git clone https://github.com/artocash/arto arto-build

cd arto-build

mkdir build && cd build && cmake .. && make

```

**Comment by nthon** [comment]
> ```
> ./artod --rpc-bind-ip=127.0.0.1 --rpc-bind-port=19451
> Failed to parse arguments: character conversion failed
> ```
> Compilation
> 
> ```
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> -- Configuring incomplete, errors occurred!
> See also "/home/arto/build/release/CMakeFiles/CMakeOutput.log".
> make: *** [cmake-release] Error 1
> 
> arto/build# make
> make: *** No targets specified and no makefile found.  Stop.
> ```
> How fix?
> Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-133-generic x86_64)

Did you fixed that? I got the same error.
