### ISSUE TITLE
./artod: error while loading shared libraries: libboost_system.so.1.59.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cchalifo999** [artocash/arto#2]
/artod: error while loading shared libraries: libboost_system.so.1.59.0: cannot open shared object file: No such file or directory from the prbult and i have boost all ready installed

**Comment by artocash** [comment]
Hello, 

You need boost devel (1.59.0).

**Comment by cchalifo999** [comment]
> 
> 
> Hello,
> 
> You need boost devel (1.59.0).

i have boost devel 1.69.0 i am on fedora 30 server

**Comment by artocash** [comment]
I am build it using boost devel 1.59. You need to build it manually to use boost 1.69.

**Comment by cchalifo999** [comment]
k ty

**Comment by artocash** [comment]
OK I will close this one .
Thanks,
